"""remove  unique key from column photo in table student

Revision ID: 0a605ad4c36d
Revises: 
Create Date: 2023-08-01 14:43:17.352375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a605ad4c36d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_photo_key', 'student', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('student_photo_key', 'student', ['photo'])
    # ### end Alembic commands ###
