"""update model and create new table

Revision ID: 6de366199f00
Revises: ad4bd03beaff
Create Date: 2023-09-14 10:40:26.166802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6de366199f00'
down_revision = 'ad4bd03beaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('validation_uuid_mention_fkey', 'validation', type_='foreignkey')
    op.drop_column('validation', 'uuid_mention')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation', sa.Column('uuid_mention', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('validation_uuid_mention_fkey', 'validation', 'mention', ['uuid_mention'], ['uuid'])
    # ### end Alembic commands ###
