"""update model and create new table

Revision ID: ad4bd03beaff
Revises: 0a605ad4c36d
Create Date: 2023-09-14 09:42:33.689716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad4bd03beaff'
down_revision = '0a605ad4c36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('uuid_mention', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('uuid_journey', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('num_carte', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['num_carte'], ['student.num_carte'], ),
    sa.ForeignKeyConstraint(['uuid_journey'], ['journey.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_mention'], ['mention.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
